title: Vinoth Kumar Rajendran
description: Personal website of Vinoth Kumar Rajendran
about_me: Software Engineer | Homelab

social:
  github: 'https://github.com/vinothvkr'
  twitter: 'https://twitter.com/_vinothvkr'

comments:
  enabled: true
  repo: vinothvkr/vinothvkr.github.io
  repo_id: R_kgDOLzfcvg
  category: Comments
  category_id: DIC_kwDOLzfcvs4ClkLF
  mapping: pathname
  input_position: bottom
  lang: en
  reactions_enabled: 1
  loading: lazy
